### ISSUE TITLE
Update for latest patch.

### ISSUE THREAD

**Issue by hsieharrison** [any-other-guy/Endless-Chaos-LostArk#74]
Sad to see the author is no longer updating this bot. I've been working on improving this bot myself after hearing the news. Currently, I have updated screenshot folder for gunslinger, added support for demonic impulse, and added support for pinnacle glav (although this was really just # out in the code). Updated the mouse X,Y locations for bifrost and updated mouse X,Y for chaos dungeon locations. Updated mouse X,Y locations for charPositions up to 18 (although this only works if you have at least 16 chars). 

Currently working on automating leapstone dailies (can only automate Mokomoko island and Hestera Garden dailies, will add more once the other leapstone dailies are added from Korea). I do want to ask how mouse x,y positions are calculated. Everything I've used returns different values than the ones used in the script.

I would also like to potentially add more to the readme for guides on how to better optimize skills for higher success rate. (For ex, even if skills are directional, they should still be listed as non-directional because AOE spells are better selfcast.

**Comment by jaredrklein** [comment]
Will you be making it public? I was waiting to confirm he was'nt updating before putting in the effort aside from a few x,y updates.

There might be a few of us who could who could get it in better shape if the original guy is cool with it.

**Comment by BoredCoder95** [comment]
I've been working on my own fork for quite some time, but never thought to make it public on account of this one still being updated by the original author.  If they are no longer supporting, I'll make mine public and share it.

https://github.com/BoredCoder95/ChaosBot

Any feedback and help would be appreciated.

**Comment by hsieharrison** [comment]
So far starters, I actually customized mine to do mokomoko, Examine the Brilliant Spring, and Writer's Life: Fan Meeting. The last one is an honor shard daily since it's easy to script. 

I also added the option in my edit to only do lopangs as an option. All you really have to do is just subtract 2 from the current character's aura lol.

I would love to collaborate on some ideas to maybe improve the script for more consistent floor 3 clears. I have two ideas for this. One idea is just resurrecting with phoenix plumes if you die in floor 3. Second idea is just forcing your character to die once upon entry to floor 3 before clearing. Curious to know your thoughts on it. 

Also adding in a feature to resume the bot after the script fails would be a cool feature to have. I currently just edit the 'main character" value to whichever character the script failed on but its not the best way to resume since it assumes everybody has aura again. Probably a simple feature but I haven't looked too much into adding it since editting the main character value works good enough for me.

I don't really use github but I would love to somehow get in touch on discord or something and collaborate on it.

**Comment by jaredrklein** [comment]
Damn ight ill hit you up in Discord and check out that new fork today/tomorrow and see how we can all link up to collab.

**Comment by BoredCoder95** [comment]
>I would love to collaborate on some ideas to maybe improve the script for more consistent floor 3 clears. I have two ideas for this. One idea is just resurrecting with phoenix plumes if you die in floor 3. Second idea is just forcing your character to die once upon entry to floor 3 before clearing. Curious to know your thoughts on it.

Main issue I found with floor 3 clearing was related to the time limit.  I got around that by editing it like so:
![image](https://github.com/any-other-guy/LostArk-Endless-Chaos/assets/26286818/f6771fb9-4d47-4ac0-ad3c-f4d13e90e4b3)
The image it looks for is the exit button that shows up once the timer hits 0:00

**Comment by jaredrklein** [comment]
@BoredCoder95 I haven't really figured out the mouse thing either. I have not been able to try changing my display settings on my monitor to match lost ark, which may be the reason it does ever match other than that my only guess is that its program specific? Got caught up with stuff, will try to reach out on Discord soon.

**Comment by BoredCoder95** [comment]
@jaredrklein the test.py file that is included with this bot is what I used to figure out mouse positions for edits, it just constantly outputs the x,y of your current mouse location, along with the rbg at that point

**Comment by Kerine999** [comment]
Happy to collab as well - re: failing floor 3, I have mine using phoenix plumes on floor 3 specifically - it tends to eat at most 1 per run if the character dies partway through, and prevents them from having a hard time getting back to the mobs. Looks like the repository @BoredCoder95 linked I'm not able to access, though.

**Comment by 5475616e** [comment]
Anyone have any an up to date version of this?

**Comment by ElPichiii** [comment]
@5475616e i was looking for the same, did you try the bot?

**Comment by 5475616e** [comment]
Yeh tried it and keeps getting ImageNotFoundException  # Raise PyAutoGUI's ImageNotFoundException.
Tried to reinstall Pyautogui still no luck at the moment

**Comment by Mxxinn** [comment]
So i removed the exception wrapper in pyautogui

Then changed the setting in PyScreeze to False
# For version 1.0.0, USE_IMAGE_NOT_FOUND_EXCEPTION is set to True by default.
USE_IMAGE_NOT_FOUND_EXCEPTION = False

Works fine now

**Comment by ElPichiii** [comment]
I dont know anything about Python, so can you please explain how to remove the exception wrapper? Is like comenting the lines?

**Comment by Mxxinn** [comment]
yeah, it's one line starting with @ above the locateonscreen function

**Comment by ElPichiii** [comment]
Thanks mate, ill try it later at night

**Comment by Mxxinn** [comment]
yeah, give me a shout if need help, currently i've added support for Voldis/Elgacia and workingg on Sharpshooter abilities

**Comment by ElPichiii** [comment]
Sure, ill let you know everything, ill tell you if it works well and if it not

**Comment by ElPichiii** [comment]
like this?
![image](https://github.com/any-other-guy/LostArk-Endless-Chaos/assets/90940144/f66d2924-7e99-4da8-888d-fc09febb422e)

**Comment by ElPichiii** [comment]
like this? i cant find PyScreeze to change the setting
![image](https://github.com/any-other-guy/LostArk-Endless-Chaos/assets/90940144/560f47ce-e3ec-46ff-a385-4e59aa1b44b0)

**Comment by Mxxinn** [comment]
No, 

So i removed the exception wrapper in pyautogui Then changed the setting in PyScreeze to False.

pyautogui and PyScreeze are the libraries you downloaded. Should take you to the function if you click+ctrl locateOnScreen.

![image](https://github.com/any-other-guy/LostArk-Endless-Chaos/assets/159916904/7085dcf5-8441-4164-be50-b84295ef2982)
This is the wrapper starts with @

![image](https://github.com/any-other-guy/LostArk-Endless-Chaos/assets/159916904/fa2eac92-1e2c-484b-925b-343e70a1acbf)
this setting needs to be false

**Comment by 5475616e** [comment]
Thanks that worked for me, Only had to change image not found to false

**Comment by ElPichiii** [comment]
i might me dumb but:
Endless Chaos starting in seconds...
Remember to turn on Auto-disassemble
city loaded
Traceback (most recent call last):
  File "C:\Users\pichi\Downloads\Endless-Chaos\bot.py", line 3731, in <module>
    main()
  File "C:\Users\pichi\Downloads\Endless-Chaos\bot.py", line 282, in main
    enterChaos()
  File "C:\Users\pichi\Downloads\Endless-Chaos\bot.py", line 505, in enterChaos
    _curr = config["characters"][states["currentCharacter"]]
            ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: 'int' object is not subscriptable
that happened to me, so i dont even enter the into chaos, can it be the order?
![20240214123119_1](https://github.com/any-other-guy/LostArk-Endless-Chaos/assets/90940144/edb3ed9b-f325-4b6b-a78e-b4997b2d6f8a)

**Comment by Mxxinn** [comment]
something with your characters or main character settings 

 `"mainCharacter": 0,  # must be in between number 0 to len(characters) - 1 (0 is the first character)`
 
 
 `characters = [
    {
        "index": 0,
        "class": "deathblade",
        "ilvl-endless": 1610,
        "ilvl-aor": 1610,
        "lopang": False,
        "guildDonation": True,
        "rapport": False,
    },
    {
        "index": 1,
        "class": "deathblade",
        "ilvl-endless": 1600,
        "ilvl-aor": 1600,
        "lopang": False,
        "guildDonation": True,
        "rapport": False,
    },
    {
        "index": 2,
        "class": "sharpshooter",
        "ilvl-endless": 1580,
        "ilvl-aor": 1580,
        "guildDonation": True,
        "rapport": False,
    },
    {
        "index": 3,
        "class": "paladin",
        "ilvl-endless": 1560,
        "ilvl-aor": 1560,
        "lopang": False,
        "guildDonation": True,
        "rapport": False,
    },
    {
        "index": 4,
        "class": "berserker",
        "ilvl-endless": 1540,
        "ilvl-aor": 1540,
        "lopang": False,
        "guildDonation": True,
        "rapport": False,
    },
    {
        "index": 5,
        "class": "striker",
        "ilvl-endless": 1520,
        "ilvl-aor": 1520,
        "lopang": False,
        "guildDonation": True,
        "rapport": False,
    },
`

**Comment by ElPichiii** [comment]
so if I am a reaper, what number do I have to put?

**Comment by SkDoesToasterBath** [comment]
Anyone knows if it still works or has a working Version of it?

**Comment by ElPichiii** [comment]
If you do what mxxinn said, yeh

**Comment by SkDoesToasterBath** [comment]
> If you do what mxxinn said, yeh

I literally have 0 knowledge with what everyone is talking here but on a scale on 1 to 10 how hard can it be to do what he said?

**Comment by ElPichiii** [comment]
I have 0 knowledge too, so i think maybe 2/3, its not hard, the only hard part is to find the file, thats all

**Comment by SkDoesToasterBath** [comment]
> I have 0 knowledge too, so i think maybe 2/3, its not hard, the only hard part is to find the file, thats all

Tbh I have 0 clue what exactly to do with all the things shown in the github link - for example what I have to download or what programs I need in order to make everything work too

**Comment by SkDoesToasterBath** [comment]
> Well, go to the main Page, and click code, download the Zip, extract the Zip, if you dont have Python installed download It too, open a terminal and go to the folder, install the requirements doing, pip install -r requirements.txt, go to config and set Up tour your config, and do abilities too, then go to the files you have to change the thing that are Up in the comments and you are good to go

For now I just followed the readme Instructions - do I have to do the "pip install -r rqeuirements.txt" still?

**Comment by ElPichiii** [comment]
No if you did this https://github.com/any-other-guy/LostArk-Endless-Chaos?tab=readme-ov-file#3-start-running-script

**Comment by SkDoesToasterBath** [comment]
> No if you did this https://github.com/any-other-guy/LostArk-Endless-Chaos?tab=readme-ov-file#3-start-running-script

For Classes can I just add "souleater" without having to worry about anything?

**Comment by ElPichiii** [comment]
Idk, i didnt understand well how to config It, i think there is a number for each class, and you put that number, and also config the abilities, that IS VERY IMPORTANT, i didnt get the tool running well, but at least the issues that i had were solved touching the other files mxxinn told me

**Comment by SkDoesToasterBath** [comment]
> Idk, i didnt understand well how to config It, i think there is a number for each class, and you put that number, and also config the abilities, that IS VERY IMPORTANT, i didnt get the tool running well, but at least the issues that i had were solved touching the other files mxxinn told me

For the config.py how did you add your characters exactly? Did you put in the index number from them and how did you pick multiple?

**Comment by ElPichiii** [comment]
Yeah i think the Index number IS what i puta, and i dont know if you can pick multiple

**Comment by SkDoesToasterBath** [comment]
Wait I just read now that it just enters low level chaos dungeon is that still the case?

**Comment by ElPichiii** [comment]
I think you can config that too

**Comment by SkDoesToasterBath** [comment]
LMAO this might be the dumbest question but where do I put the commands to start the script? :X

**Comment by ElPichiii** [comment]
Yeh, dumb as fuck, open cmd, go to the folder where you have the bot and run python bot.py or if you have python3 do python3 bot.py

**Comment by SkDoesToasterBath** [comment]
Figured it out

**Comment by ElPichiii** [comment]
Bro i was typing haha

**Comment by SkDoesToasterBath** [comment]
Okay so how do I get into the things Mxxinn mentioned?

Wanna add each other in dc so I dont have to spam this thread? ^^'

**Comment by ElPichiii** [comment]
Dc: pichi4362
I just searched the file on Explorer, and i i didnt have It, i searched the lib folder, one of then i didnt have It installed so i downloaded It and search the file again

**Comment by Vinh1984** [comment]
I asked if AUTO was completed? If used for TAIWAN server, can it be used? And do I need to adjust anything else?

**Comment by JustaBeba** [comment]
> I asked if AUTO was completed? If used for TAIWAN server, can it be used? And do I need to adjust anything else?

You need to modify the login method and almost all in-game screenshots.
The program can run on the Taiwan server. Its algorithm is better than I imagined.
